tags:
  - Tasks
summary: Get all tasks
operationId: getTasks
description: Returns all tasks.
responses:
  '200':
    description: Tasks retrieved successfully
    content:
      application/json:
        schema:
          type: object
          required:
            - status
            - message
            - data
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Tüm kartlar başarıyla getirildi!
            data:
              type: array
              items:
                $ref: '../../../swagger/components/schemas/task.yaml'
  '401':
    $ref: '../../../swagger/components/responses/401.yaml'
